# Generated by Django 5.0.6 on 2024-08-04 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=512)),
                ('date', models.DateTimeField()),
                ('message_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('thread_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='queue_api.event')),
            ],
            bases=('queue_api.event',),
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='queue_api.event')),
                ('is_rendering', models.BooleanField(default=False)),
            ],
            bases=('queue_api.event',),
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_message_id', models.BigIntegerField(null=True)),
                ('second_message_id', models.BigIntegerField(null=True)),
                ('first_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_member', to='queue_api.queuemember')),
                ('second_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_member', to='queue_api.queuemember')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_api.telegramgroup')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_api.telegramgroup'),
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128, null=True)),
                ('tz', models.IntegerField(default=3)),
                ('is_started', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(through='queue_api.GroupMember', to='queue_api.telegramgroup')),
            ],
        ),
        migrations.AddField(
            model_name='queuemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_api.telegramuser'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_api.telegramuser'),
        ),
        migrations.AddField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_api.telegramuser'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='user_queue',
            field=models.ManyToManyField(through='queue_api.QueueMember', to='queue_api.queue'),
        ),
        migrations.AddField(
            model_name='queuemember',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_api.queue'),
        ),
    ]
