# Generated by Django 5.0.6 on 2024-07-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='tz',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='tz',
            field=models.IntegerField(default=3),
        ),
    ]
