# Generated by Django 5.0.6 on 2024-08-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramgroup',
            name='main_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='queue_api.telegramuser'),
        ),
    ]
