# Generated by Django 5.0.6 on 2024-08-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_api', '0002_rename_message_event_text_remove_event_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='is_main_admin',
            field=models.BooleanField(default=False),
        ),
    ]
