# Generated by Django 5.0.6 on 2024-07-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_api', '0002_remove_queue_tz_telegramuser_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
