# Generated by Django 5.0.6 on 2024-07-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_api', '0003_telegramuser_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuemember',
            name='has_in_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queuemember',
            name='has_out_request',
            field=models.BooleanField(default=False),
        ),
    ]
