# Generated by Django 5.0.6 on 2024-08-08 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_api', '0003_deadlinerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_api.deadline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_api.telegramuser')),
            ],
        ),
    ]
