# Generated by Django 5.0.6 on 2024-08-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_api', '0004_deadlinestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('group_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='queue_api.groupmember')),
                ('date', models.DateTimeField(auto_now=True)),
                ('prev_rating', models.SmallIntegerField(default=0)),
                ('rating', models.SmallIntegerField(default=0)),
                ('scholarship', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='queue_api.telegramgroup')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
