# Generated by Django 5.0.6 on 2024-08-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_api', '0006_alter_student_group_member_alter_studentgroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='is_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='thread_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
