# Generated by Django 5.0.6 on 2024-11-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_api', '0007_studentgroup_is_session_studentgroup_thread_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='scholarship',
            field=models.FloatField(default=100),
        ),
    ]
