# Generated by Django 5.0.6 on 2024-07-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_api', '0007_queue_is_rendering_queue_renders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='renders',
        ),
    ]
