# Generated by Django 5.0.6 on 2024-08-02 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_api', '0008_remove_queue_renders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=512)),
                ('date', models.DateTimeField()),
                ('message_id', models.BigIntegerField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_creator', to='queue_api.telegramuser')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_group', to='queue_api.telegramgroup')),
            ],
        ),
    ]
