services:
  postgres:
    hostname: host
    image:
      postgres:14.11
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
    container_name: bot
    environment:
      - host=host
    links:
      - postgres

volumes:
  db_data: