# Generated by Django 5.0.6 on 2024-07-08 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
                ('tz', models.IntegerField()),
                ('message_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('thread_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_time', models.DateTimeField(auto_now_add=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_api.queue')),
            ],
        ),
        migrations.AddField(
            model_name='queue',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_api.telegramgroup'),
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('tg_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('is_admin', models.BooleanField()),
                ('group', models.ManyToManyField(to='queue_api.telegramgroup')),
                ('queue', models.ManyToManyField(through='queue_api.QueueMember', to='queue_api.queue')),
            ],
        ),
        migrations.AddField(
            model_name='queuemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queue_api.telegramuser'),
        ),
        migrations.AddField(
            model_name='queue',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='queue_api.telegramuser'),
        ),
    ]
