# Generated by Django 5.0.6 on 2024-07-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
