# Generated by Django 5.0.6 on 2024-07-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_api', '0002_alter_telegramuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='queue',
            field=models.ManyToManyField(null=True, through='queue_api.QueueMember', to='queue_api.queue'),
        ),
    ]
