# Generated by Django 5.0.6 on 2024-07-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_api', '0003_alter_telegramuser_queue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='group',
            new_name='groups',
        ),
    ]
